In [73]:
# Imports
import numpy as np 

In [96]:
# Activation function
def sigmoid(x):
    return (1/(1+np.exp(-x)))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return (x * (1 - x))

In [97]:
# Each row is a training example, each column is a feature  [X1, X2, X3]
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)

In [98]:
y.shape

(4, 1)

In [111]:
# Class definition
class FullyConnectedNeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np.zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self):
        for i in range(5000):
            self.output = self.feedforward()
            self.backprop()
        print("Weights1:")
        print(self.weights1)
        print("-------------")
        print("Weights2:")
        print(self.weights2)
        print("-------------")
        print("Output:")
        print(self.layer1)
        print("Actual Output:")
        print(self.layer2)
        

In [112]:
nn=FullyConnectedNeuralNetwork(X,y)

In [113]:
nn.train()

Weights1:
[[-0.22845041  6.76038411  3.29273348  4.91598591]
 [ 2.88802053  6.07464294  4.56777481 -3.50399249]
 [-1.20342801 -2.67799867 -5.97736474  2.03600994]]
-------------
Weights2:
[[-3.56206606]
 [10.87721325]
 [-8.79413859]
 [-5.05567149]]
-------------
Output:
[[0.23086227 0.06428603 0.00252933 0.88452258]
 [0.84350067 0.96759919 0.1963055  0.18725291]
 [0.19280957 0.98341227 0.0638881  0.99904413]
 [0.81093562 0.9999612  0.86796904 0.96917128]]
Actual Output:
[[0.00978442]
 [0.99220988]
 [0.98783823]
 [0.01051276]]
