In [1]:
from mxnet import nd, gpu, gluon, autograd
from mxnet.gluon import nn
from mxnet.gluon.data.vision import datasets, transforms
import time

OSError: [WinError 1455] The paging file is too small for this operation to complete

In [2]:
a = mx.nd.ones((2, 3))
b = a * 2 + 1
b.asnumpy()

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [3]:
b


[[3. 3. 3.]
 [3. 3. 3.]]
<NDArray 2x3 @cpu(0)>

In [4]:
a = mx.nd.ones((2, 3), mx.gpu())
b = a * 2 + 1
b.asnumpy()

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [5]:
b


[[3. 3. 3.]
 [3. 3. 3.]]
<NDArray 2x3 @gpu(0)>

In [6]:
from mxnet import nd

In [7]:
nd.array(((1,2,3),(5,6,7)))


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [8]:
x = nd.ones((2,3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [9]:
y = nd.random.uniform(-1,1,(2,3))
y


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

In [10]:
x = nd.full((2,3), 2.0)
x


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>