In [1]:
from mxnet import nd, gpu, gluon, autograd
from mxnet.gluon import nn
from mxnet.gluon.data.vision import datasets, transforms
import time

In [2]:
x = nd.ones((3,4), ctx=gpu())
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @gpu(0)>

In [5]:
y = nd.random.uniform(shape=(3,4), ctx=gpu())
y


[[0.33810216 0.03127927 0.2290985  0.7409259 ]
 [0.51678467 0.48066086 0.16954684 0.6476759 ]
 [0.53596294 0.5642074  0.96124417 0.1492511 ]]
<NDArray 3x4 @gpu(0)>

In [6]:
x+y


[[1.3381021 1.0312793 1.2290986 1.7409259]
 [1.5167847 1.4806609 1.1695468 1.6476759]
 [1.5359629 1.5642073 1.9612441 1.1492511]]
<NDArray 3x4 @gpu(0)>

In [7]:
net = nn.Sequential()
net.add(nn.Conv2D(channels=6, kernel_size=5, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        nn.Conv2D(channels=16, kernel_size=3, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        nn.Flatten(),
        nn.Dense(120, activation="relu"),
        nn.Dense(84, activation="relu"),
        nn.Dense(10))

In [8]:
net.load_parameters('net.params', ctx=gpu(0))

In [9]:
x = nd.random.uniform(shape=(1,1,28,28), ctx=gpu(0))

In [10]:
x


[[[[0.7001983  0.17011374 0.60112673 0.95502114 0.2680663  0.6209958
    0.5171364  0.6870395  0.16168559 0.3268807  0.7434975  0.08614445
    0.5981972  0.27792847 0.7921206  0.9761957  0.8317468  0.342489
    0.25129503 0.65938723 0.60817873 0.876243   0.4718275  0.7968017
    0.95747185 0.7950684  0.9890477  0.47706157]
   [0.71780425 0.09504712 0.04413635 0.35977882 0.6484804  0.7330086
    0.24588132 0.45458525 0.05942941 0.4102934  0.4055069  0.953852
    0.48173082 0.94077986 0.6544448  0.5204195  0.51366657 0.26824725
    0.80470335 0.97785443 0.92405874 0.9958267  0.6741915  0.9845137
    0.8434614  0.1203739  0.87103236 0.48559695]
   [0.61703134 0.9908552  0.68019736 0.1992495  0.44177395 0.9425102
    0.3280242  0.92394745 0.34218395 0.95857066 0.37051064 0.8758296
    0.922072   0.6729734  0.89934814 0.52331066 0.18379742 0.8056709
    0.81154263 0.39171046 0.63809115 0.773261   0.61185527 0.9028712
    0.63188154 0.29460967 0.6304658  0.36110425]
   [0.5505457  0.1194505

In [11]:
net(x)


[[ 0.5298992   0.45112437  1.1455954  -0.3102256  -0.5669769  -1.0804445
   1.1742709  -0.7607171   0.9428171  -1.4268461 ]]
<NDArray 1x10 @gpu(0)>

NameError: name 'mxnet' is not defined

In [14]:
import mxnet

In [16]:
mxnet.__version__

'1.5.0'