In [1]:
import mxnet as mx
from mxnet import nd

In [3]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
x=x.reshape(3,4)

In [7]:
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [8]:
nd.empty((3,4))


[[0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.497e-42 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.ones((2,3,4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [10]:
x=nd.arange(12).reshape((3,4))
y=nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1],])

In [11]:
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.dot(x,y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [14]:
mx.random.seed(1)

In [15]:
x=nd.empty(shape=(6,4))
x


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 6x4 @cpu(0)>

In [16]:
x=nd.random_normal(shape=(6,4))
print(x)


[[ 0.03629482 -0.49024424 -0.9501793   0.03751943]
 [-0.7298465  -2.0401056   1.4821309   1.040828  ]
 [-0.45256865  0.3116043  -0.8367378  -0.7883006 ]
 [ 0.1266448  -0.17841923  0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264   0.84155583 -0.61584127]
 [ 0.01961146 -0.24421656 -0.13420728 -0.5180439 ]]
<NDArray 6x4 @cpu(0)>


In [18]:
y=nd.random_normal(shape=(6,4))
c=x+y
print(c)


[[ 1.8724551  -2.0465856  -1.2356508  -0.3459363 ]
 [ 0.9321232  -2.4715092   0.1445694   0.53817594]
 [-0.42166427 -1.1315897  -1.2186371  -1.2546431 ]
 [ 0.7005224  -0.06302024  1.6270034   0.52408874]
 [ 2.9280353  -1.532439    0.28568214 -0.5190774 ]
 [-2.3133159   2.0129976  -0.09880844 -1.0147622 ]]
<NDArray 6x4 @cpu(0)>


In [19]:
result= nd.zeros(shape=(6,4))
print(result)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 6x4 @cpu(0)>


In [20]:
result[:]=x+y

In [21]:
print(result)


[[ 1.8724551  -2.0465856  -1.2356508  -0.3459363 ]
 [ 0.9321232  -2.4715092   0.1445694   0.53817594]
 [-0.42166427 -1.1315897  -1.2186371  -1.2546431 ]
 [ 0.7005224  -0.06302024  1.6270034   0.52408874]
 [ 2.9280353  -1.532439    0.28568214 -0.5190774 ]
 [-2.3133159   2.0129976  -0.09880844 -1.0147622 ]]
<NDArray 6x4 @cpu(0)>


In [23]:
a=nd.ones(shape=(5))
print(a)


[1. 1. 1. 1. 1.]
<NDArray 5 @cpu(0)>


In [24]:
b=a.asnumpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
print(type(b))

<class 'numpy.ndarray'>


In [26]:
c=nd.array(b)
print(c)


[1. 1. 1. 1. 1.]
<NDArray 5 @cpu(0)>


In [27]:
d=nd.array(b, mx.cpu())

In [28]:
d


[1. 1. 1. 1. 1.]
<NDArray 5 @cpu(0)>

In [30]:
d=nd.array(b, ctx=mx.gpu())

MXNetError: [01:03:30] C:\Jenkins\workspace\mxnet\mxnet\src\storage\storage.cc:119: Compile with USE_CUDA=1 to enable GPU usage