In [4]:
import numpy as np

In [3]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    
     def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [39]:
input=np.array([[0,0,1],
                [1,1,1],
                [1,0,1],
                [0,1,1]])

In [40]:
input.shape[1]

3

In [41]:
np.random.seed(1)

In [42]:
weights1= np.random.rand(input.shape[1],4) 

In [43]:
weights1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [44]:
np.random.seed(1)

In [45]:
weights2 =np.random.rand(4,1)

In [46]:
weights2

array([[4.17022005e-01],
       [7.20324493e-01],
       [1.14374817e-04],
       [3.02332573e-01]])

In [47]:
y=np.array([[0,1,1,0]]).T

In [48]:
y

array([[0],
       [1],
       [1],
       [0]])

In [50]:
output=np.zeros(y.shape)

In [51]:
output

array([[0.],
       [0.],
       [0.],
       [0.]])

In [52]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [53]:
def sigmoid_derivative(x):
    return (x*(1-x))

In [54]:
layer1 = sigmoid(np.dot(input, weights1))

In [59]:
np.dot(input, weights1)

array([[0.39676747, 0.53881673, 0.41919451, 0.6852195 ],
       [0.96054537, 1.35147982, 0.6055691 , 1.3331128 ],
       [0.81378948, 1.25914123, 0.41930889, 0.98755207],
       [0.54352337, 0.63115533, 0.60545473, 1.03078023]])

In [60]:
input.shape

(4, 3)

In [61]:
weights1.shape

(3, 4)

In [55]:
layer1

array([[0.59791076, 0.63153712, 0.60329049, 0.66490264],
       [0.72323098, 0.79437146, 0.64692939, 0.79135506],
       [0.69291643, 0.77887824, 0.60331786, 0.72860414],
       [0.63263166, 0.65275138, 0.64690327, 0.73706713]])

In [56]:
input

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [57]:
weights1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [62]:
0*4.17022005e-01+0*1.46755891e-01+1*3.96767474e-01

0.396767474

In [63]:
sigmoid(0.396767474)

0.5979107638435494

In [64]:
output = sigmoid(np.dot(layer1, weights2))

In [65]:
output

array([[0.71204652],
       [0.75271308],
       [0.74466466],
       [0.72250622]])

In [66]:
sigmoid_derivative(output)

array([[0.20503627],
       [0.1861361 ],
       [0.19013921],
       [0.20049098]])